name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create deployment directory
        run: |
          mkdir deploy
          cp -r * deploy/ || true
          cp -r .* deploy/ || true 2>/dev/null || true
      
      - name: Create config file
        run: |
          mkdir -p deploy/config
          cat > deploy/config/config.js << 'EOL'
          const config = {
            apiKey: '${{ secrets.FIREBASE_API_KEY }}',
            authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
            databaseURL: '${{ secrets.FIREBASE_DATABASE_URL }}',
            projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
            storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
            messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
            appId: '${{ secrets.FIREBASE_APP_ID }}'
          };
          export default config;
          EOL
      
      - name: List files
        run: |
          ls -la deploy/config/
          cat deploy/config/config.js
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          force_orphan: true